resolver: lts-10.3

packages:
- '.'
- location:
    git: https://github.com/charles-cooper/interpolate
    commit: a97d737769449dee5f2410e5ed236d0716d61306
- location:
    git: https://github.com/charles-cooper/map-exts
    commit: 442211d2b3e9daae1c727524c359ca8d6261ab5d

extra-deps:
- data-fix-0.0.3
- map-exts-0.2.0.0

flags: {}

extra-package-dbs: []
